services:
  - type: web
    name: backend
    env: node
    plan: free
    branch: main
    rootDir: backend
    buildCommand: npm install --force
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production

  - type: cron
    name: daily-job
    env: node
    plan: free
    branch: main
    rootDir: backend
    schedule: "*/15 * * * *" # every 15 mins
    command: node src/scripts/notifications/celebrate_notification.js
    envVars:
      - key: NODE_ENV
        value: production
