services:
  - type: web
    name: backend
    env: node
    plan: free
    branch: main
    rootDir: backend
    buildCommand: npm install --force
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
