name: Daily Push Notification Job

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: # 🚀 Allows manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: main-backend

    defaults:
      run:
        working-directory: ./backend

    env:
      NODE_ENV: production
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      JWT_ACCESS_TOKEN: ${{ secrets.JWT_ACCESS_TOKEN }}
      JWT_REFRESH_TOKEN: ${{ secrets.JWT_REFRESH_TOKEN }}
      ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
      VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY }}
      VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🛠️ Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 📦 Install dependencies
        run: npm install --force

      - name: 🚀 Run script
        run: node src/scripts/notifications/celebrate_notification.js
